local _, addon = ...

addon.AlertMessage = "Extra LFG rewards available"

addon.MonitoringSettingsTitle = "Monitoring Settings"
addon.RoleSettingsTitle = "Role Settings"
addon.MonitorDungeonsText = "Monitor Dungeons"
addon.MonitorDungeonsTooltip = "Monitor LFG Dungeons for role shortages"
addon.MonitorRaidsText = "Monitor Raids"
addon.MonitorRaidsTooltip = "Monitor LFG Raids for role shortages"
addon.PlayAlertText = "Play Alert"
addon.PlayAlertTooltip = "Play an alert sound when there is a role shortage"
addon.ConsiderLockoutText = "Consider Lockout"
addon.ConsiderLockoutTooltip = "Do not alert for instances with active lockout"
addon.IgnoreTank = "Ignore Tank Role"
addon.IgnoreTankTooltip = "Check this if your class has a tank spec, but you do not want to perform this role"
addon.IgnoreHealer = "Ignore Healer Role"
addon.IgnoreHealerTooltip = "Check this if your class has a healing spec, but you do not want to perform this role"
addon.IgnoreDamage = "Ignore Damage Role"
addon.IgnoreDamageTooltip = "Check this if your class has a damage spec, but you do not want to perform this role"